apiVersion: v1
kind: Service
metadata:
  name: cotree-service
  namespace: cotree-namespace
spec:
  selector:
    app: cotree
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
